name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 4.0.7

jobs:
  build-web:
    name: Web
    concurrency: ci-web-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build (Linux)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
          cd build
          make -j12

      - name: Build (Web)
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B embuild
          cd embuild
          make -j12

      - name: Test
        run: |
          cd embuild
          make test

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor