name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  EM_VERSION: 3.1.34
  HOST: ${{ secrets.sftp_host }}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Build
        run: |
          wget "https://$HOST/libbinaryen.a" -O third_party/libs/libbinaryen.a
          make clean
          make -f Makefile.wasm -j`nproc`

      - name: Upload files
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.sftp_host }}
          user: ${{ secrets.sftp_username }}
          pass: ${{ secrets.sftp_password }}
          port: ${{ secrets.sftp_port }}
          localDir: "editor/"
          remoteDir: "/cyth/"
