name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 4.0.7
  NODE_VERSION: 23

jobs:
  build:
    name: Linux and Web
    concurrency: ci-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (Linux)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
          cd build
          make -j12

      - name: Build (Web)
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B embuild
          cd embuild
          make -j12

      - name: Test (Linux)
        run: |
          cd build
          make test

      - name: Test (Web)
        run: |
          cd embuild
          make test

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor

  build-windows:
    name: Windows
    concurrency: ci-windows-${{ github.ref }}
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
          cmake.exe -S . -B winbuild -G "Visual Studio 17 2022"
          cd winbuild
          msbuild cyth.sln