name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 4.0.7
  NODE_VERSION: 23

jobs:
  build-linux:
    name: Linux (x64)
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build (WASM)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DWASM=1 -S . -B build
          cd build
          make -j4

      - name: Test (WASM)
        run: |
          cd build
          make test
          make testwasm

      - name: Clean up
        run: |
          rm -rf build

      - name: Build (MIR)
        run: |
          mkdir build
          zig cc third_party/mir/mir.c third_party/mir/mir-gen.c third_party/bdwgc/extra/gc.c src/main.c src/jit.c src/checker.c src/environment.c src/memory.c src/lexer.c src/map.c src/parser.c -Ithird_party/mir -Ithird_party/bdwgc/include -fsigned-char -O3 -s -target x86_64-linux-gnu.2.5 -o build/cyth
          zig cc third_party/mir/mir.c third_party/mir/mir-gen.c third_party/bdwgc/extra/gc.c src/jit.c src/checker.c src/environment.c src/memory.c src/lexer.c src/map.c src/parser.c -Ithird_party/mir -Ithird_party/bdwgc/include -fsigned-char -O3 -s -target x86_64-linux-gnu.2.5 -c -o build/cyth.o
          zig ar rcs build/libcyth.a build/cyth.o

      - name: Test (MIR)
        run: |
          cd build
          node ../test/_test.js ./cyth
      
      - name: Bundle
        run: |
          cp src/include/cyth.h build/
          cd build
          zip cyth.zip cyth cyth.h libcyth.a  
      
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cyth.zip
          asset_name: cyth-linux-x86_64.zip
          tag: Build
          overwrite: true

  build-linux-arm64:
    name: Linux (ARM64)
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build (WASM)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DWASM=1 -S . -B build
          cd build
          make -j4

      - name: Test (WASM)
        run: |
          cd build
          make test
          make testwasm

      - name: Clean up
        run: |
          rm -rf build

      - name: Build (MIR)
        run: |
          mkdir build
          zig cc third_party/mir/mir.c third_party/mir/mir-gen.c third_party/bdwgc/extra/gc.c src/main.c src/jit.c src/checker.c src/environment.c src/memory.c src/lexer.c src/map.c src/parser.c -Ithird_party/mir -Ithird_party/bdwgc/include -fsigned-char -O3 -s -target aarch64-linux-gnu.2.17 -o build/cyth
          zig cc third_party/mir/mir.c third_party/mir/mir-gen.c third_party/bdwgc/extra/gc.c src/jit.c src/checker.c src/environment.c src/memory.c src/lexer.c src/map.c src/parser.c -Ithird_party/mir -Ithird_party/bdwgc/include -fsigned-char -O3 -s -target aarch64-linux-gnu.2.17 -c -o build/cyth.o
          zig ar rcs build/libcyth.a build/cyth.o

      - name: Test (MIR)
        run: |
          cd build
          node ../test/_test.js ./cyth
      
      - name: Bundle
        run: |
          cp src/include/cyth.h build/
          cd build
          zip cyth.zip cyth cyth.h libcyth.a  
      
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cyth.zip
          asset_name: cyth-linux-arm64.zip
          tag: Build
          overwrite: true
          
  build-web:
    name: Web
    concurrency: ci-web-${{ github.ref }}
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (Emscripten)
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B embuild
          cd embuild
          make -j3

      - name: Test (Emscripten)
        run: |
          cd embuild
          make test

      - name: Package VSCode Extension
        run: |
          cd embuild
          make package

      - name: Publish VSCode Extension
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: editor/extension/cyth-0.0.1.vsix
          asset_name: cyth-vscode-extension.vsix
          tag: Build
          overwrite: true

      - name: Publish (Web)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor

  build-macos:
    name: MacOS
    concurrency: ci-macos-${{ github.ref }}
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (WASM)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DWASM=1 -S . -B build
          cd build
          make -j3

      - name: Test (WASM)
        run: |
          cd build
          make test
          make testwasm

      - name: Clean up
        run: |
          rm -rf build

      - name: Build (MIR)
        run: |
          cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -S . -B build
          cd build
          make -j3

      - name: Test (MIR)
        run: |
          cd build
          make test

      - name: Bundle
        run: |
          cp src/include/cyth.h build/
          cd build
          zip cyth.zip cyth cyth.h libcyth.a  

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cyth.zip
          asset_name: cyth-macos-universal.zip
          tag: Build
          overwrite: true

  build-windows:
    name: Windows (x64)
    concurrency: ci-windows-${{ github.ref }}
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}  

      - name: Build and Test (WASM)
        run: |
          cmake.exe -DWASM=1 -S . -B build -G "Visual Studio 17 2022"
          cd build
          msbuild test.vcxproj
          msbuild testwasm.vcxproj

      - name: Build (MIR)
        run: |
          cmake.exe -S . -B winbuild -G "Visual Studio 17 2022"
          cd winbuild
          msbuild cyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=x64
          msbuild libcyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=x64

      - name: Test (MIR)
        run: |
          cd winbuild
          msbuild test.vcxproj -property:Configuration=Release -property:Platform=x64
        
      - name: Bundle
        run: |
          copy src\include\cyth.h winbuild\Release\
          cd winbuild\Release
          tar.exe -a -c -f cyth.zip cyth.exe cyth.lib cyth.h

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: winbuild/Release/cyth.zip
          asset_name: cyth-windows-x86_64.zip
          tag: Build
          overwrite: true

  build-windows-arm64:
    name: Windows (ARM64)
    concurrency: ci-windows-arm64-${{ github.ref }}
    runs-on: windows-11-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}  

      - name: Build and Test (WASM)
        run: |
          cmake.exe -DWASM=1 -S . -B build -G "Visual Studio 17 2022"
          cd build
          msbuild test.vcxproj
          msbuild testwasm.vcxproj

      - name: Build (MIR)
        run: |
          cmake.exe -S . -B winbuild -G "Visual Studio 17 2022"
          cd winbuild
          msbuild cyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=ARM64
          msbuild libcyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=ARM64

      - name: Test (MIR)
        run: |
          cd winbuild
          msbuild test.vcxproj -property:Configuration=Release -property:Platform=ARM64
        
      - name: Bundle
        run: |
          copy src\include\cyth.h winbuild\Release\
          cd winbuild\Release
          tar.exe -a -c -f cyth.zip cyth.exe cyth.lib cyth.h

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: winbuild/Release/cyth.zip
          asset_name: cyth-windows-arm64.zip
          tag: Build
          overwrite: true