name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 3.1.34

jobs:
  build-web:
    name: Web
    concurrency: ci-web-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build
        run: |
          make web -j8

      - name: Test
        run: |
          make test

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor
