name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 4.0.7
  NODE_VERSION: 23

jobs:
  build:
    name: Linux
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (MIR)
        run: |
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -S . -B build
          cd build
          make -j4

      - name: Test (MIR)
        run: |
          cd build
          make test
      
      - name: Bundle (MIR)
        run: |
          cp src/include/cyth.h build/
          cd build
          zip cyth.zip cyth cyth.h libcyth.a  
      
      - name: Publish (MIR)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cyth.zip
          asset_name: cyth-x86_64-linux.zip
          tag: Build
          overwrite: true
          
  build-web:
    name: Web
    concurrency: ci-web-${{ github.ref }}
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (MIR)
        run: |
          cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -S . -B build
          cd build
          make -j3

      - name: Test (MIR)
        run: |
          cd build
          make test

      - name: Bundle (MIR)
        run: |
          cp src/include/cyth.h build/
          cd build
          zip cyth.zip cyth cyth.h libcyth.a  

      - name: Build (Emscripten)
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B embuild
          cd embuild
          make -j3

      - name: Test (Emscripten)
        run: |
          cd embuild
          make test

      - name: Publish (Web)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor

      - name: Publish (MIR)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/cyth.zip
          asset_name: cyth-universal-macos.zip
          tag: Build
          overwrite: true

  build-windows:
    name: Windows (x64)
    concurrency: ci-windows-${{ github.ref }}
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}  

      - name: Build (MIR)
        run: |
          cmake.exe -S . -B winbuild -G "Visual Studio 17 2022"
          cd winbuild
          msbuild cyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=x64
          msbuild libcyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=x64

      - name: Test (MIR)
        run: |
          cd winbuild
          msbuild test.vcxproj
        
      - name: Bundle
        run: |
          copy src\include\cyth.h winbuild\Release\
          cd winbuild\Release
          tar.exe -a -c -f cyth.zip cyth.exe cyth.lib

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: winbuild/Release/cyth.zip
          asset_name: cyth-x86_64-windows.zip
          tag: Build
          overwrite: true

  build-windows-arm64:
    name: Windows (ARM64)
    concurrency: ci-windows-arm64-${{ github.ref }}
    runs-on: windows-11-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}  

      - name: Build (MIR)
        run: |
          cmake.exe -S . -B winbuild -G "Visual Studio 18 2026"
          cd winbuild
          msbuild cyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=ARM64
          msbuild libcyth.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=ARM64

      - name: Test (MIR)
        run: |
          cd winbuild
          msbuild test.vcxproj
        
      - name: Bundle
        run: |
          copy src\include\cyth.h winbuild\Release\
          cd winbuild\Release
          tar.exe -a -c -f cyth.zip cyth.exe cyth.lib

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: winbuild/Release/cyth.zip
          asset_name: cyth-arm64-windows.zip
          tag: Build
          overwrite: true