name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches: [master]

env:
  EM_VERSION: 4.0.7
  NODE_VERSION: 23

jobs:
  build:
    name: Linux and Web
    concurrency: ci-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}

      - name: Build (MIR) (Windows)
        run: |
          export PATH=~/my_msvc/opt/msvc/bin/x64:$PATH
          CC=cl CXX=cl cmake -S . -B winbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SYSTEM_NAME=Windows
          cd winbuild
          make -j12

      - name: Test (MIR) (Windows)
        run: |
          export PATH="/home/ubuntu/.wine/drive_c/Program Files/nodejs/":$PATH
          cd winbuild
          make test

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build (MIR)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
          cd build
          make -j12

      - name: Test (MIR)
        run: |
          cd build
          make test

      - name: Build (WASM)
        run: |
          cmake -DWASM=1 -DCMAKE_BUILD_TYPE=Debug -S . -B build
          cd build
          make -j12

      - name: Test (WASM)
        run: |
          cd build
          make test

      - name: Build (Emscripten)
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B embuild
          cd embuild
          make -j12

      - name: Test (Emscripten)
        run: |
          cd embuild
          make test

      - name: Publish (Web)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: editor